post_install() {
	mv -f etc/os-release_archleaf etc/os-release
	mv -f usr/lib/os-release_archleaf usr/lib/os-release
	mv -f etc/issue_archleaf etc/issue
	mv -f etc/lsb-release_archleaf etc/lsb-release
	        
	if [ -f /etc/default/grub ]; then
		sed -i s/GRUB_DISTRIBUTOR=\"Arch\"/GRUB_DISTRIBUTOR=\"Crystal\"/g etc/default/grub
		grub-mkconfig -o /boot/grub/grub.cfg
	fi
}

post_upgrade() {
	post_install
}
